#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("baidumapsdk.demo.Resource", IsApplication=true)]

namespace baidumapsdk.demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_fri_box = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_down = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_on = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_style = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int custom_loc = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ground_overlay = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_search = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_en = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_gcoding = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_geo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_marka = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_markb = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_markc = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_markd = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_marke = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_markf = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_markg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon_markh = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon_marki = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int icon_markj = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int icon_st = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int main_icon_compass = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int main_icon_follow = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int nav_turn_via_1 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int next_ = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int next_down_ = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int pop = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int popup = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int popup_down = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int popup_left = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int popup_middle = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int popup_right = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int popup_side = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int pre_ = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int pre_down_ = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int RadioGroup = 2131099655;
			
			// aapt resource value: 0x7f060037
			public const int addrshare = 2131099703;
			
			// aapt resource value: 0x7f060028
			public const int allcitylist = 2131099688;
			
			// aapt resource value: 0x7f060001
			public const int bmapView = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int bmapView8 = 2131099654;
			
			// aapt resource value: 0x7f06004f
			public const int boundsSearch = 2131099727;
			
			// aapt resource value: 0x7f06001b
			public const int button = 2131099675;
			
			// aapt resource value: 0x7f060003
			public const int button1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int button2 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int button3 = 2131099653;
			
			// aapt resource value: 0x7f06001d
			public const int city = 2131099677;
			
			// aapt resource value: 0x7f060023
			public const int city_list = 2131099683;
			
			// aapt resource value: 0x7f06001c
			public const int cityid = 2131099676;
			
			// aapt resource value: 0x7f060026
			public const int citylist_layout = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int clButton = 2131099684;
			
			// aapt resource value: 0x7f06002b
			public const int clear = 2131099691;
			
			// aapt resource value: 0x7f06005b
			public const int custombutton = 2131099739;
			
			// aapt resource value: 0x7f06000d
			public const int customicon = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int defaulticon = 2131099660;
			
			// aapt resource value: 0x7f060022
			public const int del = 2131099682;
			
			// aapt resource value: 0x7f060049
			public const int desc = 2131099721;
			
			// aapt resource value: 0x7f060050
			public const int detailsSearch = 2131099728;
			
			// aapt resource value: 0x7f060055
			public const int display = 2131099733;
			
			// aapt resource value: 0x7f06003a
			public const int doubleClick = 2131099706;
			
			// aapt resource value: 0x7f060058
			public const int drive = 2131099736;
			
			// aapt resource value: 0x7f060057
			public const int end = 2131099735;
			
			// aapt resource value: 0x7f06004b
			public const int geocode = 2131099723;
			
			// aapt resource value: 0x7f06004a
			public const int geocodekey = 2131099722;
			
			// aapt resource value: 0x7f060027
			public const int hotcitylist = 2131099687;
			
			// aapt resource value: 0x7f060033
			public const int key = 2131099699;
			
			// aapt resource value: 0x7f06002f
			public const int lat = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int layout = 2131099696;
			
			// aapt resource value: 0x7f06003e
			public const int lefttop = 2131099710;
			
			// aapt resource value: 0x7f060052
			public const int listView = 2131099730;
			
			// aapt resource value: 0x7f060025
			public const int localButton = 2131099685;
			
			// aapt resource value: 0x7f060029
			public const int localmap_layout = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int localmaplist = 2131099690;
			
			// aapt resource value: 0x7f06002d
			public const int lon = 2131099693;
			
			// aapt resource value: 0x7f060002
			public const int map = 2131099650;
			
			// aapt resource value: 0x7f060016
			public const int map1 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int map2 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int map3 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int map4 = 2131099673;
			
			// aapt resource value: 0x7f060035
			public const int map_next_data = 2131099701;
			
			// aapt resource value: 0x7f06001a
			public const int navi_info = 2131099674;
			
			// aapt resource value: 0x7f06004e
			public const int nearbySearch = 2131099726;
			
			// aapt resource value: 0x7f060042
			public const int next = 2131099714;
			
			// aapt resource value: 0x7f060040
			public const int nextline = 2131099712;
			
			// aapt resource value: 0x7f060008
			public const int normal = 2131099656;
			
			// aapt resource value: 0x7f06003c
			public const int overlook = 2131099708;
			
			// aapt resource value: 0x7f060013
			public const int overlookangle = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int overlookbutton = 2131099666;
			
			// aapt resource value: 0x7f060031
			public const int panorama = 2131099697;
			
			// aapt resource value: 0x7f060036
			public const int poishore = 2131099702;
			
			// aapt resource value: 0x7f060046
			public const int popdown = 2131099718;
			
			// aapt resource value: 0x7f060044
			public const int popinfo = 2131099716;
			
			// aapt resource value: 0x7f060043
			public const int popleft = 2131099715;
			
			// aapt resource value: 0x7f060047
			public const int popright = 2131099719;
			
			// aapt resource value: 0x7f060041
			public const int pre = 2131099713;
			
			// aapt resource value: 0x7f06000b
			public const int radioGroup = 2131099659;
			
			// aapt resource value: 0x7f060054
			public const int ratio = 2131099732;
			
			// aapt resource value: 0x7f06004d
			public const int regionSearch = 2131099725;
			
			// aapt resource value: 0x7f060056
			public const int remove = 2131099734;
			
			// aapt resource value: 0x7f06002c
			public const int reset = 2131099692;
			
			// aapt resource value: 0x7f06004c
			public const int reversegeocode = 2131099724;
			
			// aapt resource value: 0x7f06003f
			public const int righttop = 2131099711;
			
			// aapt resource value: 0x7f060032
			public const int road = 2131099698;
			
			// aapt resource value: 0x7f06003b
			public const int rotate = 2131099707;
			
			// aapt resource value: 0x7f060011
			public const int rotateangle = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int rotatebutton = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int savescreen = 2131099669;
			
			// aapt resource value: 0x7f06001f
			public const int scan = 2131099679;
			
			// aapt resource value: 0x7f060039
			public const int scroll = 2131099705;
			
			// aapt resource value: 0x7f06001e
			public const int search = 2131099678;
			
			// aapt resource value: 0x7f060034
			public const int searchkey = 2131099700;
			
			// aapt resource value: 0x7f060020
			public const int start = 2131099680;
			
			// aapt resource value: 0x7f060014
			public const int state = 2131099668;
			
			// aapt resource value: 0x7f060009
			public const int statellite = 2131099657;
			
			// aapt resource value: 0x7f060021
			public const int stop = 2131099681;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f06002e
			public const int textView2 = 2131099694;
			
			// aapt resource value: 0x7f060051
			public const int text_Info = 2131099729;
			
			// aapt resource value: 0x7f060045
			public const int textcache = 2131099717;
			
			// aapt resource value: 0x7f060048
			public const int title = 2131099720;
			
			// aapt resource value: 0x7f06000a
			public const int traffice = 2131099658;
			
			// aapt resource value: 0x7f060059
			public const int transit = 2131099737;
			
			// aapt resource value: 0x7f060053
			public const int update = 2131099731;
			
			// aapt resource value: 0x7f06005a
			public const int walk = 2131099738;
			
			// aapt resource value: 0x7f060038
			public const int zoom = 2131099704;
			
			// aapt resource value: 0x7f06003d
			public const int zoomControl = 2131099709;
			
			// aapt resource value: 0x7f06000e
			public const int zoombutton = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int zoomlevel = 2131099663;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_cloud_search_demo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_customroute = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_fragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_geometry = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_itemizedoverlay = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_layers = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_locationoverlay = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_mapcontrol = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int activity_mutimap = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int activity_navi_demo = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int activity_offline = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int activity_overlay = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int activity_panorama_demo = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int activity_panorama_geo_selector = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int activity_panorama_main = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int activity_panorama_poi_selector = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int activity_poisearch = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int activity_share_demo = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int activity_share_demo_activity = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int activity_textoverlay = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int activity_uisetting = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int buslinesearch = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int custom_text_view = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int demo_info_item = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int geocoder = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int lbssearch = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int main = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int offline_localmap_list = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int routeplan = 2130903069;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040037
			public const int cloud_search_tips = 2130968631;
			
			// aapt resource value: 0x7f040003
			public const int demo_desc_basemap = 2130968579;
			
			// aapt resource value: 0x7f04002a
			public const int demo_desc_bus = 2130968618;
			
			// aapt resource value: 0x7f040033
			public const int demo_desc_cloud = 2130968627;
			
			// aapt resource value: 0x7f040011
			public const int demo_desc_control = 2130968593;
			
			// aapt resource value: 0x7f040027
			public const int demo_desc_geocode = 2130968615;
			
			// aapt resource value: 0x7f04001b
			public const int demo_desc_geometry = 2130968603;
			
			// aapt resource value: 0x7f04000f
			public const int demo_desc_layers = 2130968591;
			
			// aapt resource value: 0x7f040018
			public const int demo_desc_location = 2130968600;
			
			// aapt resource value: 0x7f040009
			public const int demo_desc_map_fragment = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int demo_desc_mutimap = 2130968588;
			
			// aapt resource value: 0x7f040030
			public const int demo_desc_navi = 2130968624;
			
			// aapt resource value: 0x7f04002d
			public const int demo_desc_offline = 2130968621;
			
			// aapt resource value: 0x7f04001e
			public const int demo_desc_overlay = 2130968606;
			
			// aapt resource value: 0x7f040006
			public const int demo_desc_panorama = 2130968582;
			
			// aapt resource value: 0x7f040021
			public const int demo_desc_poi = 2130968609;
			
			// aapt resource value: 0x7f040024
			public const int demo_desc_route = 2130968612;
			
			// aapt resource value: 0x7f04003d
			public const int demo_desc_share = 2130968637;
			
			// aapt resource value: 0x7f040015
			public const int demo_desc_ui = 2130968597;
			
			// aapt resource value: 0x7f040001
			public const int demo_name_basemap = 2130968577;
			
			// aapt resource value: 0x7f040028
			public const int demo_name_bus = 2130968616;
			
			// aapt resource value: 0x7f040031
			public const int demo_name_cloud = 2130968625;
			
			// aapt resource value: 0x7f040010
			public const int demo_name_control = 2130968592;
			
			// aapt resource value: 0x7f040025
			public const int demo_name_geocode = 2130968613;
			
			// aapt resource value: 0x7f040019
			public const int demo_name_geometry = 2130968601;
			
			// aapt resource value: 0x7f04000d
			public const int demo_name_layers = 2130968589;
			
			// aapt resource value: 0x7f040016
			public const int demo_name_location = 2130968598;
			
			// aapt resource value: 0x7f040007
			public const int demo_name_map_fragment = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int demo_name_mutimap = 2130968586;
			
			// aapt resource value: 0x7f04002e
			public const int demo_name_navi = 2130968622;
			
			// aapt resource value: 0x7f04002b
			public const int demo_name_offline = 2130968619;
			
			// aapt resource value: 0x7f04001c
			public const int demo_name_overlay = 2130968604;
			
			// aapt resource value: 0x7f040004
			public const int demo_name_panorama = 2130968580;
			
			// aapt resource value: 0x7f04001f
			public const int demo_name_poi = 2130968607;
			
			// aapt resource value: 0x7f040022
			public const int demo_name_route = 2130968610;
			
			// aapt resource value: 0x7f04003c
			public const int demo_name_share = 2130968636;
			
			// aapt resource value: 0x7f040013
			public const int demo_name_ui = 2130968595;
			
			// aapt resource value: 0x7f040002
			public const int demo_title_basemap = 2130968578;
			
			// aapt resource value: 0x7f040029
			public const int demo_title_bus = 2130968617;
			
			// aapt resource value: 0x7f040032
			public const int demo_title_cloud = 2130968626;
			
			// aapt resource value: 0x7f040012
			public const int demo_title_control = 2130968594;
			
			// aapt resource value: 0x7f040026
			public const int demo_title_geocode = 2130968614;
			
			// aapt resource value: 0x7f04001a
			public const int demo_title_geometry = 2130968602;
			
			// aapt resource value: 0x7f04000e
			public const int demo_title_layers = 2130968590;
			
			// aapt resource value: 0x7f040017
			public const int demo_title_location = 2130968599;
			
			// aapt resource value: 0x7f040008
			public const int demo_title_map_fragment = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int demo_title_mutimap = 2130968587;
			
			// aapt resource value: 0x7f04002f
			public const int demo_title_navi = 2130968623;
			
			// aapt resource value: 0x7f04002c
			public const int demo_title_offline = 2130968620;
			
			// aapt resource value: 0x7f04001d
			public const int demo_title_overlay = 2130968605;
			
			// aapt resource value: 0x7f040005
			public const int demo_title_panorama = 2130968581;
			
			// aapt resource value: 0x7f040020
			public const int demo_title_poi = 2130968608;
			
			// aapt resource value: 0x7f040023
			public const int demo_title_route = 2130968611;
			
			// aapt resource value: 0x7f04003b
			public const int demo_title_share = 2130968635;
			
			// aapt resource value: 0x7f040014
			public const int demo_title_ui = 2130968596;
			
			// aapt resource value: 0x7f040034
			public const int key_error = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int navi_tip = 2130968629;
			
			// aapt resource value: 0x7f04003a
			public const int panorama_geo_tips = 2130968634;
			
			// aapt resource value: 0x7f040039
			public const int panorama_poi_tips = 2130968633;
			
			// aapt resource value: 0x7f040038
			public const int panorama_tips = 2130968632;
			
			// aapt resource value: 0x7f04003e
			public const int share_tip = 2130968638;
			
			// aapt resource value: 0x7f040036
			public const int title_activity_cloud_search_demo = 2130968630;
			
			// aapt resource value: 0x7f04003f
			public const int title_activity_panorama_activity_main = 2130968639;
			
			// aapt resource value: 0x7f040042
			public const int title_activity_panorama_demo = 2130968642;
			
			// aapt resource value: 0x7f040041
			public const int title_activity_panorama_geo_selector = 2130968641;
			
			// aapt resource value: 0x7f040040
			public const int title_activity_panorama_poi_selector = 2130968640;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
